name: lol_project
version: '1.0.0'
config-version: 2

profile: lol_project

model-paths: ["models"]
test-paths: ["tests"]

models:
  lol_project:
    +catalog: workspace
    staging:
      +schema: lol_staging
      +materialized: view
    intermediate:
      +schema: lol_intermediate
      +materialized: view
    dims:
      +schema: lol_dims
      +materialized: table
    facts:
      +schema: lol_facts
      +materialized: table
    marts:
      +schema: lol_marts
      +materialized: table