name: lol_project
version: '1.0.1'
config-version: 2

profile: lol_project

model-paths: ["models"]
test-paths: ["tests"]

models:
  lol_project:
    +catalog: workspace
    staging:
      +schema: lol_staging
      +materialized: view
      +persist_docs:
        relation: true
        columns: true
    intermediate:
      +schema: lol_intermediate
      +materialized: view
      +persist_docs:
        relation: true
        columns: true
    dims:
      +schema: lol_dims
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
    facts:
      +schema: lol_facts
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
    marts:
      +schema: lol_marts
      +materialized: table
      +persist_docs:
        relation: true
        columns: true