version: 2

sources:
  - name: lol_staging
    catalog: workspace
    schema: lol_staging
    tables:
      - name: tournaments
      - name: players
      - name: teams
      - name: matches
      - name: games
      - name: player_games